[dependencies]
leptos = "0.1"
wasm-bindgen = "0.2"
futures = "0.3"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlElement", "Event"] }

[lib]
crate-type = ["cdylib"]
